name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-image.yml'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Build the Docker image step
      run: docker build . --file src/Dockerfile --tag my-image-name:$(date +%s)
    - name: Push the Docker image
      if: github.event_name == 'push'
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
