name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - '.github/workflows/docker-image.yml'


permissions:
  contents: read
  packages: write


jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: group1
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Log in to GHCR
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Set repo name to lowercase
      id: set_repo_name
      run: echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT
    - name: Build and maybe push the Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./src/Dockerfile
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: ghcr.io/${{ steps.set_repo_name.outputs.repository }}/mythapi:latest
  dep:
    runs-on: ubuntu-latest
    concurrency: group1
    steps:
      - name: Output name
        run: echo "My name ${{ vars.MY_NAME }}"
      - name: Output password
        run: echo "My name ${{ secrets.MY_PASSWORD }}"
  tst:
    runs-on: ubuntu-latest
    concurrency: 
      group: group2
      cancel-in-progress: true
    name: TEST CD JOB
    steps:
      - name: Output name
        run: echo "My name ${{ vars.MY_NAME }}"
      - name: Output password
        run: echo "My name ${{ secrets.MY_PASSWORD }}"
  prd:
    runs-on: ubuntu-latest
    concurrency: 
      group: group2
      cancel-in-progress: true
    steps:
      - name: Output name
        run: echo "My name ${{ vars.MY_NAME }}"
      - name: Output password
        run: echo "My name ${{ secrets.MY_PASSWORD }}"
      
      
